-- 1. INFRASTRUCTURE SETUP

-- Create Warehouse
CREATE OR REPLACE WAREHOUSE AIRLINE_WH 
WITH WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE;

-- Create Main Database and Schemas (Medallion Architecture)
CREATE OR REPLACE DATABASE AIRLINE_DWH;
USE DATABASE AIRLINE_DWH;

CREATE OR REPLACE SCHEMA BRONZE;
CREATE OR REPLACE SCHEMA SILVER;
CREATE OR REPLACE SCHEMA GOLD;
CREATE OR REPLACE SCHEMA UTILS;

-- Create External Stage for data ingestion
CREATE OR REPLACE STAGE AIRLINE_DWH.BRONZE.AIRLINE_STAGE;

-- Create CSV File Format for standard ingestion
CREATE OR REPLACE FILE FORMAT AIRLINE_DWH.BRONZE.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- 2. TABLE DEFINITIONS

-- Bronze Layer: Raw landing table for all CSV columns
CREATE OR REPLACE TABLE AIRLINE_DWH.BRONZE.FLIGHTS_RAW (
    PASSENGER_ID STRING, FIRST_NAME STRING, LAST_NAME STRING,
    GENDER STRING, AGE INT, NATIONALITY STRING,
    AIRPORT_NAME STRING, AIRPORT_COUNTRY_CODE STRING, COUNTRY_NAME STRING,
    AIRPORT_CONTINENT STRING, CONTINENTS STRING, DEPARTURE_DATE DATE,
    ARRIVAL_AIRPORT STRING, PILOT_NAME STRING, FLIGHT_STATUS STRING,
    TICKET_TYPE STRING, PASSENGER_STATUS STRING
);

-- Silver Layer: Filtered and cleaned data
CREATE OR REPLACE TABLE AIRLINE_DWH.SILVER.FLIGHTS_TRANSFORMED (
    FLIGHT_ID STRING, 
    ORIGIN_AIRPORT STRING,
    STATUS STRING, 
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Gold Layer: Final Fact table for BI
CREATE OR REPLACE TABLE AIRLINE_DWH.GOLD.FACT_FLIGHTS (
    FLIGHT_ID VARCHAR, 
    ORIGIN_AIRPORT VARCHAR, 
    STATUS VARCHAR
);

-- 3. STORED PROCEDURES (ETL LOGIC)

-- Procedure: Load data from Stage to Bronze
CREATE OR REPLACE PROCEDURE AIRLINE_DWH.BRONZE.LOAD_FROM_STAGE()
RETURNS STRING LANGUAGE SQL EXECUTE AS CALLER
AS
$$
BEGIN
    COPY INTO AIRLINE_DWH.BRONZE.FLIGHTS_RAW
    FROM @AIRLINE_DWH.BRONZE.AIRLINE_STAGE
    FILE_FORMAT = (FORMAT_NAME = 'AIRLINE_DWH.BRONZE.CSV_FORMAT')
    ON_ERROR = 'CONTINUE'
    FORCE = TRUE;
    RETURN 'Bronze Load Completed Successfully';
END;
$$;

-- Procedure: Transform data from Bronze to Silver
CREATE OR REPLACE PROCEDURE AIRLINE_DWH.SILVER.PROCESS_RAW_TO_SILVER()
RETURNS STRING LANGUAGE SQL EXECUTE AS CALLER
AS
$$
BEGIN
    CREATE OR REPLACE TABLE AIRLINE_DWH.SILVER.FLIGHTS_TRANSFORMED AS
    SELECT 
        PASSENGER_ID AS FLIGHT_ID,
        AIRPORT_NAME AS ORIGIN_AIRPORT,
        FLIGHT_STATUS AS STATUS
    FROM AIRLINE_DWH.BRONZE.FLIGHTS_RAW;
    RETURN 'Silver Transformation Completed Successfully';
END;
$$;

-- Procedure: Load data from Silver to Gold Fact Table
CREATE OR REPLACE PROCEDURE AIRLINE_DWH.GOLD.LOAD_TO_GOLD_PROC()
RETURNS STRING LANGUAGE SQL EXECUTE AS CALLER
AS
$$
BEGIN
    CREATE OR REPLACE TABLE AIRLINE_DWH.GOLD.FACT_FLIGHTS AS
    SELECT FLIGHT_ID, ORIGIN_AIRPORT, STATUS 
    FROM AIRLINE_DWH.SILVER.FLIGHTS_TRANSFORMED;
    RETURN 'Gold Fact Table Loaded Successfully';
END;
$$;

-- 4. DATA GOVERNANCE & SECURITY

-- Secure View for authorized reporting
CREATE OR REPLACE SECURE VIEW AIRLINE_DWH.GOLD.ON_TIME_FLIGHTS_VW AS
SELECT * FROM AIRLINE_DWH.GOLD.FACT_FLIGHTS 
WHERE STATUS = 'On Time';

-- Row Level Security Policy (Restricts view based on role)
CREATE OR REPLACE ROW ACCESS POLICY AIRLINE_DWH.UTILS.FLIGHT_STATUS_POLICY
AS (status_val string) RETURNS BOOLEAN ->
    CURRENT_ROLE() = 'ACCOUNTADMIN' OR status_val = 'On Time';

ALTER TABLE AIRLINE_DWH.GOLD.FACT_FLIGHTS 
ADD ROW ACCESS POLICY AIRLINE_DWH.UTILS.FLIGHT_STATUS_POLICY ON (STATUS);
